### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by NahuelCostaCortez** [SymposiumOrganization/Dynaformer#1]
Hi!

First of all, congratulations for the repository and the article, I find it very interesting. 
I tried to play around with the demo in streamlit but I faced some problems:

- The folder scripts/generate_dataset.py doesn't exist. I executed download_training_data.py instead but the expected path in visualize_predictions.py is different (it doesn't exist in the folders created with download_training_data.py)
- I am not sure if the saved model should be in the "runs" folder. If so, that folder does not exist after running download_training_data.py either.

I am aware that the repository is in its early days, and I have already seen some TO-DOs out there, I just wanted to let you know the problems I have encountered in case that helps to improve the reproducibility of the results.

Thanks,
Nahuel

**Comment by TommasoBendinelli** [comment]
Hello Nahuel, 
Thank you very much for trying out the repo and reporting your issues! We will look into them in the next couple of days and try to resolve them!

Best,
Tommaso

**Comment by TommasoBendinelli** [comment]
Hi Nahuel,

We have fixed the problems your mentioning, feel free to re-open the issue if anything else in unclear
