### ISSUE TITLE
HYDRA_FULL_ERROR=1

### ISSUE THREAD

**Issue by Mrzhang-hub** [SymposiumOrganization/Dynaformer#2]
Firstly, thank you for your share of this wonderful project. However, when I run `generate_dataset.py`, it sends the error: 

```

D:\Dyang_Research\Anaconda3\envs\Dynaformer\lib\site-packages\hydra\_internal\defaults_list.py:251: UserWarning: In 'generate_dataset': Defaults list is missing `_self_`. See https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
In 'generate_dataset': Could not find 'test_sets/none'

Config search path:
	provider=hydra, path=pkg://hydra.conf
	provider=main, path=file://D:\Dyang_Research\Dynaformer_StateEstimation\config
	provider=schema, path=structured://
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

I could not find the solution to tackle this problem and I hope you can help me out. 

Besides, I am really interested in this project, but I wonder when you can finish the to-do-list.

**Comment by ratheile** [comment]
Hi @Mrzhang-hub,
Thanks for posting! I get a similar output, could you solve this problem in the meantime?

**Comment by TommasoBendinelli** [comment]
Hi there, sorry for the delay. I have uploaded the missing file,

Best,
Tommaso
